/*
	* PacBio Seeder
	* Authors:
	* Patrick Finger, Robert Oller, Benjamin Ladick
	* Brief:
	* This program locates potential start locations
	* of pacbio reads generated by PBSIM
*/

#include "CommandLineArgumentHandler.h"

int main(int argc, char** argv)
{
	CommandLineArgumentHandler handler;
	handler.Execute(argc, argv);
}
